### ISSUE TITLE
Project issues

### ISSUE THREAD

**Issue by tkisason** [lpredova/pyTA#1]
Developer started new project instead of finishing the existing one (Masters thesis) :)

**Comment by ipadavic** [comment]
👍

**Comment by TheWildHorse** [comment]
I think we should mark this one as WONTFIX.

**Comment by lpredova** [comment]
fixed in https://github.com/lpredova/ressie

**Comment by tkisason** [comment]
Can confirm fixed in the following screenshot: 
![2017-03-29 10 33 17](https://user-images.githubusercontent.com/577380/27350334-56e52cd6-55fa-11e7-984e-5ba5435224ce.jpg)
